### ISSUE TITLE
entities not available

### ISSUE THREAD

**Issue by jolly12f** [aturri/ha-zcsazzurro#6]
### The problem

good morning, the device detects 24 units, but only 4 are available, the others are not avaiable 

### Version of zcsazzurro integration having the issue?

Entita 

### Version of Home Assistant Core having the issue?

Entita

**Comment by aturri** [comment]
Hi @jolly12f,
By default only entities related to power and energy generating are enabled, plus the status sensor. All others are disabled because they are not common to all ZCS devices. You can manually enable the additional sensors that you need, according to your device capabilities (if a sensor remains in unknown state, than the sensor it is not supported).
This has been designed in this way, because ZCS API does not allow to know what are the capabilities of a device in advance.

Thanks,
Andrea
